[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
create_token = "8AHDoGeCsHdgxM7QRcg6vXybN16b3A28zuF4GEMA5Ltr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/vt_id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


[test.validator]
bind_address = "0.0.0.0"
url = "https://solana-devnet.g.alchemy.com/v2/fb2tOtZi3LR_Wp"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"