[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
spl_token_minter = "3of89Z9jwek9zrFgpCWc9jZvQvitpVMxpZNsrAD2vQUD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/vt_id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


[test]
startup_wait = 50000


[test.validator]
bind_address = "0.0.0.0"
url = "https://solana-devnet.g.alchemy.com/v2/fb2BIxKbV3bRP5tPZavvFtOtZi3LR_Wp"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

