[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
fundraiser = "5XQSYWf6864N3Vb6ij6n6h4op6B2KoHxUmcor9wguRwU"

[programs.localnet]
fundraiser = "5XQSYWf6864N3Vb6ij6n6h4op6B2KoHxUmcor9wguRwU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
