[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
swap_example = "B3BAL7yCqb2ifDFUjdxdWvc7c3zwSboBMPGxafgsurev"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/vt_id.json"

[scripts]
# test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
# test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/create-amm.ts"
# test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/create-pool.ts"
# test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/swap.ts"
# test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/deposit-liquidity.ts"
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/withdraw-liquidity.ts"


# [test]
# startup_wait = 5000
# shutdown_wait = 2000
# upgradeable = false
