[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
swap_example = "GsDfoUQzLyTMisAy5cyckJTPWpW5viH52X5fHsoDcTM7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/vt_id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/withdraw-liquidity.ts"
